[variables]
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
  'echo "Installing server dependencies..."',
  'cd server',
  'npm ci --only=production'
]

[phases.build]
cmds = [
  'echo "No build step needed - this is a Node.js server"',
  'echo "Skipping frontend build - only deploying backend"'
]

[start]
cmd = 'cd server && node server.js'