[phases.setup]
cmds = ['echo "Setting up for Railway deployment..."']

[phases.install]
cmds = ['cd server && npm ci --only=production']

[phases.build]
cmds = ['echo "No build step needed for Node.js server"']

[start]
cmd = 'cd server && npm start'