services:
  # Backend API Service
  - type: web
    name: optical-website-api
    env: node
    region: oregon
    plan: starter
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    domains:
      - optical-api.onrender.com

  # Frontend Static Site
  - type: web
    name: optical-website-frontend  
    env: static
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    buildFilter:
      paths:
      - src/**
      - public/**
      - package.json
      - index.html
      - vite.config.ts
    domains:
      - optical-website.onrender.com
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html